### ISSUE TITLE
compare transient behavior to persistent behavior

### ISSUE THREAD

**Issue by MichaelBlume** [ztellman/collection-check#8]
Right now this lib will compare, say

```(-> [] (conj 3) (conj 4))``` to ```(-> (my-empty-vector) (conj 3) (conj 4))```

*or*

```(-> [] transient (conj! 3) (conj! 4) persistent!)``` to ```(-> (my-empty-vector) transient (conj! 3) (conj! 4) persistent!)```

but at no time does it compare

```(-> [] (conj 3) (conj 4))``` with ```(-> [] transient (conj! 3) (conj! 4) persistent!)```, which may well be a good place to look for bugs. To do this, the library would have to "know" that ```conj!``` is the transient version of ```conj```, which I don't think it knows right now.

**Comment by ztellman** [comment]
I'm going to close this, pending a reason.
